controllers/UserController.php
<?php
namespace isqr\scms\controllers;

use Exception;
use Yii;
use isqr\scms\components\SController;
use isqr\scms\components\SGlobal;
use isqr\scms\jobs\SEmailJob;
use isqr\scms\models\SLoginForm;
use isqr\scms\models\SPasswordChangeForm;
use isqr\scms\models\SPasswordResetForm;
use isqr\scms\models\SNotification;
use isqr\scms\models\SUser;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use yii\web\UnauthorizedHttpException;
use isqr\scms\models\SVerifyDeviceForm;
use isqr\scms\models\SUserDevice;
use yii\web\ForbiddenHttpException;
use isqr\scms\models\SActivityLog;
use isqr\scms\models\SEmailTemplate;
use yii\web\GoneHttpException;
use yii\web\HttpException;

class UserController extends SController
{	
	const LOGIN_DEVICE_PASS = 1;
	const LOGIN_DEVICE_FAIL = 2;
	const LOGIN_DEVICE_VERIFICATION_REQUIRED = 3;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    array(
                        'actions' => ['login', 'login-with-key', 'external', 'index', 'activate-device', 'verify-device', 'signup', 'reset-password'],
                        'allow' => true,
                        'roles' => ['?'],
                    ),
                    array(
        				'actions'=>array('index', 'login-with-key','login-success', 'activate-device', 'verify-device', 'signup', 'login', 'logout', 'edit', 'change-password', 'me', 'ping'),
                        'allow' => true,
        				'roles'=>array('@'),
					),
                ],
            ]
        ];
	}
	
	public function actions()
    {
        return [
            'external' => [
                'class' => 'yii\authclient\AuthAction',
				'successCallback' => [$this, 'externalSuccessCallback']
            ],
        ];
	}

	public function beforeAction($action)
    {   
		if($action->id == "external") {
			header("access-control-allow-origin: *");
			$this->enableCsrfValidation = false;
			$request = Yii::$app->getRequest();
			
			if(isset($_REQUEST['code'])){
				$_GET['code'] = $_REQUEST['code'];
			}
			if(isset($_REQUEST['id_token'])){
				$_GET['id_token'] = $_REQUEST['id_token'];
			}
		}

        return parent::beforeAction($action);
	}
	
	public function init()
	{
	    parent::init();
		$this->layout = "@scms/views/layouts/user";
	}
	
	public function actionMe()
	{
		return $this->actionIndex(0, "me");
	}
	
	public function actionIndex($id = 0, $username = "me")
	{
		if($id != 0){
			$user = SUser::find()->where(["id" => $id])->one();
			if($user==null) throw new NotFoundHttpException("Profile does not exist.");
		}
		elseif ($username!="me"){
			$user = SUser::find()->where(["username" => $username])->one();
			if($user==null) throw new NotFoundHttpException("Profile does not exist.");
		}
		else {
			$user = SGlobal::getCurrentUser();
			if($user==null)
				return $this->redirect(['/scms/user/login']);
		}
		if(SGlobal::isMe($user->id))
			$this->view->title = Yii::t('app', "My Profile");		
		else {
			if(SGlobal::getAppParam("userAllowPublicProfile") == false && !SGlobal::isAdminUser())
				throw new UnauthorizedHttpException("You are not authorized to view this profile.");
			
			$this->view->title = $user->getFullName();
		}
		$this->view->params['breadcrumbs'][] = $this->view->title;
		
		if(trim($user->about) != ""){
			$this->view->setMetaTag("description", $user->about);
			$this->view->setMetaTag("og:description", $user->about);
		}
		
		if(trim($user->image_profile) != ""){
			$this->view->setMetaTag("og:image", $user->getProfileImageUrl());
		}
		$this->view->setMetaTag("og:title", $this->view->title);
		
		$this->layout = "@scms/views/layouts/useraccount";
		return $this->render("index", array(
			'user'=>$user,
		));
	}
	
	public function actionEdit()
	{
		$user = SGlobal::getCurrentUser();
		if($user == null) {
			echo 'You are not authorized to view this page.';
			return;
		}
		
		if(isset($_POST['SUser']))
		{
			$user->attributes = $_POST['SUser'];
			if (Yii::$app->request->isPost) {
			    $user->saveProfileImage();
			    if($user->save()){
			        $this->redirect(Url::toRoute(['/scms/user/index', 'id'=>$user->id]));
			    }
			}
		}
		
		$this->view->title = Yii::t('app', "Edit Profile");
		$this->view->params['breadcrumbs'][] = ['label'=>'My Account', 'url'=>'/scms/user/index'];
		$this->view->params['breadcrumbs'][] = $this->view->title;
		
		
		$this->layout = "@scms/views/layouts/useraccount";
		return $this->render($this->getViewName(), array(
			'model'=>$user,
		));
	}
	
	public function actionSignup()
	{	
		if(isset($_REQUEST['redirect_to'])) {
			Yii::$app->session->set('login_redirect_to', $_REQUEST['redirect_to']);
		}
        
		if(!Yii::$app->user->isGuest){
			return $this->redirect(Url::toRoute(['/scms/user/login-success']));
		}

		if(SGlobal::getAppParam("userAllowSignup") !== true)
			throw new UnauthorizedHttpException();
		
		$user = new SUser();
		if(isset($_POST['SUser']))
		{
		    $user->id = SGlobal::createUniqueId();
			$user->attributes = $_POST['SUser'];
			$password = $user->password;
			$user->setPassword($user->password);
			$user->created_time = date('Y-m-d H:i:s.u');
			
			if(SGlobal::getAppParam("userAutoApproveOnSignup") === true)
				$user->status = SUser::USER_STATUS_ACTIVE;
			else 
				$user->status = SUser::USER_STATUS_INACTIVE;
			
            if($user->save())
			{
				return $this->_login($user);
			}
		}

		$this->view->title = Yii::t('app', "Register");
		$this->view->params['breadcrumbs'][] = $this->view->title;
		return $this->render($this->getViewName(), array(
			'model'=>$user,
		));
	}
	
    public function actionLoginSuccess(){
		$rt = Yii::$app->session->get('login_redirect_to');
		Yii::$app->session->remove('login_redirect_to');
		$user = SUser::getCurrentUser();
		$device = SUser::getCurrentDevice();
		$redirectAfterLogin = Url::toRoute([SGlobal::getAppParam("redirect_after_login_url", "/scms/default/index")]);
		
		if($user->force_change_password == 1) {
			$redirectAfterLogin = Url::toRoute(['/scms/user/change-password', 'scn' => SPasswordChangeForm::SCENARIO_CHANGEPASSWORD]);
		}
		
		if($device != null){
			$device->createAuthCode();
			if($device->update())
				if($rt!= null){
					$rt = urldecode($rt);
					$rt .= ((parse_url($rt, PHP_URL_QUERY) ? '&' : '?') . "code=" . $device->auth_code);
					return $this->redirect($rt);
				}
				else
					return $this->redirect($redirectAfterLogin);
			else {
				throw new HttpException("Unable to create auth code.");
			}
		}
		else {
			return $this->redirect($redirectAfterLogin);
		}
	}

	public function externalSuccessCallback($client)
    {
		$deviceLoggingEnable = SGlobal::getAppParam("device_logging_enable", false);
		$deviceVerificationEnable = SGlobal::getAppParam("device_verification_enable", false);

		if($deviceLoggingEnable == \false) {
			throw new GoneHttpException("Device logging is disabled. External authentication will not work.");
		}

		$user = SUser::getUserUsingAuth($client);
		if($user != null) {
			return $this->_login($user, true);
		}
		throw new GoneHttpException("Unable to login.");
	}

	private function _loginWithDevice($user, $verifyDevice){
		$device = SUserDevice::getDevice($user);
		if($device === true) {
			$user->login($device);
			return self::LOGIN_DEVICE_PASS;
		}
		elseif($device instanceof SUserDevice) {
			$cookies = Yii::$app->response->cookies;
			$cookies->add(new \yii\web\Cookie(['name' => '_d', 'value' => $device->id]));
			
			if($verifyDevice && !$device->isAuthenticated()){
				$subject = "Device Verification";
				$verify_device_url = Url::toRoute(["/scms/user/verify-device", 'id'=>$device->id, 'code'=>$device->pin], true);
				$activate_device_url = Url::toRoute(["/scms/user/activate-device", 'id'=>$device->id], true);
				$verify_device_button = '<a href="'.$verify_device_url.'"><img src="'.$activate_device_url.'" /></a>';

				$body = '<p>Here is the verification code to verify your device. </p>{{verify_device_code}}<p> If this message has landed in your junk mail folder, we suggest that you move the message to your inbox or permanently set our address as a safe/secure sender on your email account.</p><br/> <br/> {{signature}}';					
				
				$template = SEmailTemplate::get("user_device_verification", [
					'to_email' => $user->email,
					'to_name' => $user->getFullName(),
					'subject' => $subject,
					'content' => $body,
					'activate_device_url' => $activate_device_url,
					'verify_device_code' => $device->pin,
				]);
				Yii::$app->queue->push(new SEmailJob([
					'to_email' => $user->email,
					'to_name' => $user->getFullName(),
					'from_email' => $template->from_email,
					'from_name' => $template->from_name,
					'subject' => $template->subject,
					'content' => $template->content,
				]));
				$deviceVerificationActivationRequired = SGlobal::getAppParam("device_verification_activation_required", false);
				if($deviceVerificationActivationRequired == false) {
					$device->active = 1;
					$device->activated_time = date("Y-m-d H:i:s");
					$device->createHashKey();
					$device->save();
				}
				return self::LOGIN_DEVICE_VERIFICATION_REQUIRED;
			}
			else {
				$device->active = 1;
				$device->activated_time = date("Y-m-d H:i:s");
				$device->createHashKey();
				$device->save();
				$cookies->add(new \yii\web\Cookie(['name' => '_h', 'value' => $device->_h]));
				$user->login($device);
				return self::LOGIN_DEVICE_PASS;
			}
		}
		return self::LOGIN_DEVICE_FAIL;
	}
	
	protected function _login($user, $external = false, $force = false) {

views/user/change-password.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use isqr\scms\components\SGlobal;
use isqr\scms\models\SPasswordChangeForm;

?>
<div class="row">
<div class="col-md-6">
	<?php if(Yii::$app->session->hasFlash('submit')): ?>
		<?php echo Yii::$app->session->getFlash('submit'); ?><br/><br/>
		<?php echo Html::a('Ok', Url::base(true), array('class'=>'btn btn-primary')); ?>
	<?php else: ?>
		<?php
		$form = ActiveForm::begin([
		    'id' => 'resetpassword-form',
		    'enableAjaxValidation' => false,
		    'options' => [
		        'class' => ''
		    ]
		])?>
		<?php if($model->scenario == SPasswordChangeForm::SCENARIO_VALIDATEDCHANGEPASSWORD):?>
	    <?= $form->field($model, 'currentpassword')->passwordInput();?>
		<?php endif; ?>
	    <?= $form->field($model, 'password')->passwordInput();?>
	    <?= $form->field($model, 'confirmpassword')->passwordInput();?>
	    <?= Html::submitButton('Change', ['class' => 'btn btn-primary'])?>
		<?php ActiveForm::end()?>
	<?php endif; ?>
</div>
</div>

views/user/edit.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use isqr\scms\components\SGlobal;
?>
<?php
$form = ActiveForm::begin([
    'id' => 'profileedit-form',
    'enableAjaxValidation' => false,
    'options' => [
        'enctype'=>'multipart/form-data'
    ]
])?>
    <div class="row">
        <div class="col-md-3 profile-picture">
            <div class="form-group">
                <img class="img-responsive  img-thumbnail "  src="<?php echo $model->getProfileImageUrl($this->context->appAsset); ?>" />
            </div>
        </div>
        <div class="col-md-6" style="padding-top: 20px">
            <?php echo $form->field($model,'file')->fileInput([])->hint('Please upload square image of dimension (400 x 400)');  ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
        <?= $form->field($model, 'name');?>
        </div>
        <div class="col-md-6">
        <?= $form->field($model, 'surname');?>
        </div>
    </div>
    
    
    <?= $form->field($model, 'username')->textInput();?>
    
    <?= $form->field($model, 'intro')->textInput();?>
    <?= $form->field($model, 'about')->textArea(["rows"=>3]);?>
    <?= $form->field($model, 'gender')->inline()->radioList(array(0=>'Male',1=>'Female'));?>
    
    <?= $form->field($model, 'address')->textArea(["rows"=>2]);?>
    <div class="row">
        <div class="col-md-6">
        <?= $form->field($model, 'country');?>
        </div>
        <div class="col-md-6">
        <?= $form->field($model, 'city');?>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6">
        <?= $form->field($model, 'phone_number');?>
        </div>
        <div class="col-md-6">
        <?= $form->field($model, 'mobile_number');?>
        </div>
    </div>
	<?= Html::submitButton('Save', ['class' => 'btn btn-primary'])?>
<?php ActiveForm::end()?>

views/user/index.php
<?php use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
?>
<div class="row userprofile">
	<div class="col-md-3">
		<img class="thumbnail img-responsive" src="<?php echo $user->getProfileImageUrl($this->context->appAsset); ?>" alt="<?php echo $user->getFullName(); ?>"/>
	</div>
	<div class="col-md-9 description">
		<h1><?= $user->getFullName(); ?></h1>
		<p><i class="fa fa-envelope"></i> <strong>Email:</strong> <?php echo $user->email?></p>
		<p><i class="fa fa-user"></i> <strong>Gender:</strong> <?php echo $user->getGender();?></p>
		<p><i class="fa fa-calendar"></i> <strong>Member since:</strong> <?php echo date('F Y',strtotime($user->created_time));?></p>
	</div>
</div>





views/user/login-success.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use isqr\scms\components\SGlobal;
use isqr\scms\components\SEnum;
use yii\base\Event;
?>
Please waiting while logging in. . . 
<script>
window.location = '<?=$url;?>'
</script>

views/user/login.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use isqr\scms\components\SGlobal;
use isqr\scms\components\SEnum;
use yii\base\Event;
?>
<?php $form = ActiveForm::begin([
    'id' => 'login-form',
    'enableAjaxValidation' => false,
    'options' => [
    ]
])?>
<div class="row">
<div class="col-md-6">
	<?php $allowSignup = SGlobal::getAppParam("userAllowSignup", false);?>
	<?php if($allowSignup): ?>
	<h4><?=Yii::t('app', 'Don\'t have an account?');?> <small><a href="<?php echo Url::toRoute(['user/signup']);?>" style="color: #999999"><?=Yii::t('app', 'Create Account');?></a></small></h4>
	<?php endif;?>
	<p><?=Yii::t('app', 'If you are an existing user, login using your e-mail address and password.');?></p>
    
    <?= $form->field($model, 'email')->textInput(["placeholder"=>"Email"])->label(true)?>
    <?= $form->field($model, 'password')->passwordInput(["placeholder"=>"Password"])->label(true)?>
    <p><a href="<?php echo Url::toRoute(['user/reset-password']);?>"
		class="hint"><?=Yii::t('app', 'Have you forgotten your password?');?></a>
	</p>
    
    <p>
    <?= Html::submitButton(Yii::t('app', 'Login'), ['class' => 'btn  btn-primary'])?> 
    </p>
</div>
</div>
<?php ActiveForm::end()?>

views/user/recovery.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use isqr\scms\components\SGlobal;
?>
<div class="row">
<div class="col-md-6">
	<?php if(Yii::$app->session->hasFlash('submit')): ?>
		<?php echo Yii::$app->session->getFlash('submit'); ?><br/><br/>
		<?php echo Html::a('Ok', Url::base(true), array('class'=>'btn btn-primary')); ?>
	<?php else: ?>
		<?php
		$form = ActiveForm::begin([
		    'id' => 'resetpassword-form',
		    'enableAjaxValidation' => false,
		    'options' => [
		        'class' => ''
		    ]
		])?>
	    <?= $form->field($model, 'password')->passwordInput();?>
	    <?= $form->field($model, 'confirmpassword')->passwordInput();?>
        <?= $form->field($model, 'email')->hiddenInput(); ?>
		<?= $form->field($model, 'activate_key')->hiddenInput(); ?>
	    <?= Html::submitButton('Change', ['class' => 'btn btn-primary'])?>
		<?php ActiveForm::end()?>
	<?php endif; ?>
</div>
</div>

views/user/reset-password.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use isqr\scms\models\SPasswordResetForm;
?>
<?php
$form = ActiveForm::begin([
    'id' => 'resetpassword-form',
    'enableAjaxValidation' => false, 
	'fieldConfig' => [
		'horizontalCssClasses' => [
			'label' => 'col-sm-3',
			'wrapper' => 'col-sm-9',
		],
	],
    'options' => [
    ]
])?>
<div class="row">
<div class="col-md-6">
	
    <?php if(Yii::$app->session->hasFlash('submit')): ?>
    	<h4><?=Yii::t('app', 'Help is on its way!')?></h4>
		<p><?= Yii::$app->session->getFlash('submit'); ?></p>
		<?= Html::a(Yii::t('app', 'Ok'), Url::toRoute("/scms/user/login"), array('class'=>'btn btn-primary')); ?>
    <?php else:?>
    <h4><?=Yii::t('app', 'Relax!')?></h4>
	<p><?=Yii::t('app', 'If you\'ve forgotten your password, enter your e-mail address and we\'ll send you an e-mail telling you how to recover it.');?></p>
	<?php if($model->scenario == SPasswordResetForm::SCENARIO_CHANGEPASSWORD):?>
		<?= $form->field($model, 'password')->passwordInput();?>
		<?= $form->field($model, 'confirmpassword')->passwordInput();?>
		<?= $form->field($model, 'activation_key')->hiddenInput()->label(false)?>
		<?= $form->field($model, 'email')->hiddenInput()->label(false)?>
	<?php else:?>
		<?= $form->field($model, 'email')->textInput(["placeholder"=>Yii::t('app', "Email")])->label(true)?>
	<?php endif;?>
	<?= Html::submitButton(Yii::t('app', 'Reset'), ['class' => 'btn  btn-primary'])?>
    <?php endif; ?>
</div>
</div>
<?php ActiveForm::end()?>

views/user/signup.php
<?php
	use yii\bootstrap\ActiveForm;
	use yii\helpers\Url;
	use yii\helpers\Html;
	use isqr\scms\components\SGlobal;
    use yii\web\View;
    use isqr\scms\widgets\jsregister\JSRegister;
?>

<div class="row">
	<div class="col-md-12">
	<h4 >Already Registered? <small><a href="<?=Url::toRoute("/scms/user/login")?>" style="color: #999999">Login </a></small></h4>
	<p>Fill out the following form in order to register with us . We will save the details you provide in order to facilitate your purchases on our website.</p>
	<?php
	$form = ActiveForm::begin([
	    'id' => 'signup-form',
	    'enableAjaxValidation' => false,
		'layout' => 'horizontal',
		'class' => 'form-horizontal',   
		'fieldConfig' => [
			'horizontalCssClasses' => [
				'label' => 'col-sm-3',
				'wrapper' => 'col-sm-9',
			],
		],
	    'options' => [
	    ]
	])?>
		<h4>Your Personal Details</h4>
	    <div class="row">
	        <div class="col-md-6">
	        <?= $form->field($model, 'name')->textInput(["placeholder"=>"Name"])->label(true)?>
	        </div>
	        <div class="col-md-6">
	        <?= $form->field($model, 'surname')->textInput(["placeholder"=>"Surname"])->label(true)?>
	        </div>
	    </div>
	   
	    <div class="row">
	        <div class="col-md-6">
	        <?= $form->field($model, 'email')->textInput(["placeholder"=>"Email"])->label(true)?>
	        </div>
	        <div class="col-md-6">
	        <?= $form->field($model, 'phone_number')->textInput(["placeholder"=>"Phone No."])->label(true)?>
	        </div>
	    </div>
		<div class="row">
			<div class="col-md-6">
    			<?= $form->field($model, 'gender')->inline()->radioList(array(0=>'Male',1=>'Female'));?>
    		</div>
    	</div>
	    
	    <h4>Your Location</h4>
	    <div class="row">
	        <div class="col-md-6">
	        <?= $form->field($model, 'address')->textarea(["placeholder"=>"Address"])->label(true)?>
	        </div>
	        <div class="col-md-6">
	        <?= $form->field($model, 'city')->textInput(["placeholder"=>"City"])->label(true)?>
	        </div>
	    </div>
	    
	    <h4>Your Password</h4>
	    <div class="row">
	        <div class="col-md-6">
	        <?= $form->field($model, 'password')->passwordInput(["placeholder"=>"Password"])->label(true)?>
	        </div>
	        <div class="col-md-6">
			<?= $form->field($model, 'confirm_password')->hiddenInput()->label(false)?>
	        </div>
	    </div>
	    <p class="hint text-danger">Note: By pressing Register button, you agree to our terms of use and privacy policy.</p>
	    
	    <?= Html::submitButton('Register', ['class' => 'btn btn-primary'])?>
	<?php ActiveForm::end()?>
	</div>
</div>


<?php JSRegister::begin(["position" => View::POS_READY]); ?>
	<script>
		$('#suser-password').on('input', function(e){
			$('#suser-confirm_password').val(e.target.value)
		})
	</script>
<?php JSRegister::end(); ?>

views/user/verify-device.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use isqr\scms\components\SGlobal;
use isqr\scms\components\SEnum;
use yii\base\Event;
?>

<div class="row">
<div class="col-md-6">
<?php
$form = ActiveForm::begin([
    'id' => 'verify-device-form',
    'enableAjaxValidation' => false,
    'options' => [
    ]
])?>
<p>Please check your email. The verification code has been sent to your email address to verify this device.</p>
<?= $form->field($model, 'code')->passwordInput(["placeholder"=>"Verification Code"])->label(true)?>
<p>
<?= Html::submitButton('Continue', ['class' => 'btn  btn-primary'])?> 
</p>
<?php ActiveForm::end()?>
</div>
</div>